### ISSUE TITLE
Crash on launch with RBSRequestErrorDomain error 5

### ISSUE THREAD

**Issue by johankool** [KhaosT/SimpleVM#1]
I couldn't get the app to launch on Big Sur 11.0 Beta (20A5323l) using Xcode 12.0 beta 3 (12A8169g) due to a code signing issue causing it to report RBSRequestErrorDomain error 5. I found that renaming the entitlement `com.apple.vm.networking` to `com.apple.security.virtualization` made it work.

**Comment by KhaosT** [comment]
`com.apple.vm.networking` was determine not necessary since we are using NAT network instead of a bridged one. I updated the repo to reflect the change. Thanks for reporting this ^^
