### ISSUE TITLE
What type of file should be passed for the bootableImageURL parameter?

### ISSUE THREAD

**Issue by sy1995** [KhaosT/SimpleVM#3]
The document told me add a RAW disk image，how to create a RAW disk image?

thx

**Comment by KhaosT** [comment]
I was testing with Ubuntu's Live CD ISO, and that one works without modification.

**Comment by sy1995** [comment]
You mean is the Ubuntu's ISO？I drag this ISO to image,and tap “start”, it's hint error.
Below is the console error message:
2020-11-19 15:56:16.531565+0800 SimpleVM[13178:986902] Failed: Error Domain=VZErrorDomain Code=1 "The virtual machine failed to start" UserInfo={NSDebugDescription=The virtual machine failed to start}

**Comment by JacopoMangiavacchi** [comment]
Amazing stuff, thank you for sharing!!

Unfortunately I'm having same issue too.  I'm using focal-desktop-arm64.iso as I wasn't able to find ubuntu desktop arm image.  Unfortunately the screen capture you shared on twitter is covered and I can't see real file name.  Can you share here that file names ?  Thank you so much

**Comment by KhaosT** [comment]
I'm also using `focal-desktop-arm64.iso`

You can extract `vmlinuz` and `initrd` following this:

1. `sudo mkdir /Volumes/Ubuntu`
2. `sudo hdiutil attach -nomount PATH_TO_YOUR_ISO`
3. `sudo mount -t cd9660 /dev/diskX Ubuntu` (X is what the `FDisk_partition_scheme` from step 2)
4. `open /Volumes/Ubuntu/casper`
5. Copy `vmlinuz` and `initrd` to your own folder
6. Rename `vmlinuz` to `vmlinuz.gz` and unarchive it

Now you should have all the things to run the VM.

**Comment by JacopoMangiavacchi** [comment]
Thank you sir

**Comment by sy1995** [comment]
Thank you sir
