### ISSUE TITLE
expose Ethernet interface, Mac Mini M1

### ISSUE THREAD

**Issue by erwincoumans** [KhaosT/SimpleVM#6]
Thanks for providing this! SimpleVM with Ubuntu 20.04 works well, and it exposes the Wifi interface, and Ubuntu inside SimpleVM can access internet just fine.

Is there any way to expose some local Ethernet interface? The Mac Mini is connected over Ethernet to some machine (Mac mini Ethernet address 192.168.123.100, remote machine is 192.168.123.10, and I'd like to connect the SimpleVM Ubuntu to that local machine.

**Comment by KhaosT** [comment]
Unfortunately, bridged interface requires a special entitlement that Apple only grants to companies making virtualization softwares 😅

**Comment by kenji21** [comment]
You are talking of these APIs : https://developer.apple.com/documentation/virtualization/vzvirtionetworkdeviceconfiguration 

From the https://developer.apple.com/documentation/virtualization page, there is:
```
Important
A process must have the com.apple.security.virtualization entitlement to use the Virtualization APIs.
```

And it is already in [SimpleVM.entitlements](https://github.com/KhaosT/SimpleVM/blob/master/SimpleVM/SimpleVM.entitlements) file

**Comment by KhaosT** [comment]
I'm talking about [this one](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_networking).

**Comment by kenji21** [comment]
I was [editing](https://github.com/KhaosT/SimpleVM/issues/6#issuecomment-744192093) to point the [vzvirtionetworkdeviceconfiguration ](https://developer.apple.com/documentation/virtualization/vzvirtionetworkdeviceconfiguration) when you replied to vmnet APIs

**Comment by erwincoumans** [comment]
Networking is possible between host and VM, so one workaround is to write software that performs the communication  (routing/forwarding messages) between programs running in the VM (on Ubuntu) and a third machine connected to the host (M1). I measured the latency to send/receive messages over TCP or UDP and it is around 0.1ms roundtrip for my Python C++-extension.

**Comment by kenji21** [comment]
OK, under the hood, [VZBridgedNetworkDeviceAttachment](https://developer.apple.com/documentation/virtualization/vzbridgednetworkdeviceattachment) also uses [com.apple.vm.networking](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_networking) entitlement
